### ISSUE TITLE
Unable to edit metamodel

### ISSUE THREAD

**Issue by AlexanderNeumann** [rwth-acis/syncmeta#114]
I am unable to edit an existing metamodel (bot metamodel). 
If I change any value all the attribute types are gone. 

![edit-bug](https://user-images.githubusercontent.com/10010710/226481283-2ce520f1-f070-43bc-ace9-3dbff3a8739d.gif)

**Comment by AlexanderNeumann** [comment]
Maybe something with the dropdowns?

**Comment by lakhoune** [comment]
The issue was related to a yjs event listener in the canvas that was still using the old yjs<13 syntax and consequently did not get triggered when the value was changed. 
That event listener was also responsible for triggering the EntityManager that stored the values in the metamodel.

**Comment by lakhoune** [comment]
Reopening issue since all keyselection values are now updated instead of only the selected one
