### ISSUE TITLE
Input fields are not stored properly 

### ISSUE THREAD

**Issue by AlexanderNeumann** [rwth-acis/syncmeta#134]
Sometimes if I enter something in an input field it is not stored in yjs. After a reload the field is empty again. 
![store](https://user-images.githubusercontent.com/10010710/234289768-329ad42e-d96b-485c-82f3-67479e41274e.gif)

**Comment by AlexanderNeumann** [comment]
They are stored if i add (and delete) a new element

**Comment by Aran30** [comment]
Still seems to happen

**Comment by lakhoune** [comment]
> Still seems to happen

@Aran30 Could you give more information to which input fields you are referring?

**Comment by Aran30** [comment]
happened to me e.g. with the incoming message node

**Comment by lakhoune** [comment]
> > Still seems to happen
> 
> @Aran30 Could you give more information to which **input fields** you are referring?

What **INPUT FIELDS** are you reffering to ?

**Comment by Aran30** [comment]
well the ones defined at the beginning of the issue

**Comment by Aran30** [comment]
no, i mean any input field that appears on the right side in the property widget
(the gif only takes the leadsto arrow as an example)

**Comment by lakhoune** [comment]
could not be reproduced

**Comment by Aran30** [comment]
![example](https://github.com/rwth-acis/syncmeta/assets/50965489/4dfced04-f60a-4f38-9bda-47c06e42b7de)
This field here

**Comment by Aran30** [comment]
Of course note that it's only an example, so it is not exclusive to the "intent keyword" field of the Incoming Message element but might happen to other fields as well

**Comment by Aran30** [comment]
![fieldgone](https://github.com/rwth-acis/syncmeta/assets/50965489/d9cd5df3-ee27-47a2-8390-bc479a35f6e7)

**Comment by lakhoune** [comment]
> ![fieldgone](https://user-images.githubusercontent.com/50965489/238659927-d9cd5df3-ee27-47a2-8390-bc479a35f6e7.gif)
 
is this also reproducable in the latest syncmeta version?

**Comment by Aran30** [comment]
yes

**Comment by Aran30** [comment]
seems to work now
