### ISSUE TITLE
Changing metamodel deletes imported model

### ISSUE THREAD

**Issue by Aran30** [rwth-acis/syncmeta#140]
If one imports another metamodel to a space which already contains a model, the created model is deleted. 
Sometimes, a metamodel might only receive a small change such as an additional parameter beind added to an element. 
This should not cause the old model to be deleted as it is still compatible.

**Comment by lakhoune** [comment]
This is a change that was specifically made by me, because in my opinion, in most cases where you change the metamodel, the model will not be compatible anymore

**Comment by Aran30** [comment]
In all my time working on bots and updating metamodels, I'd say that 80% of the time, the model was still compatible with the updated metamodel.  
Models only lose their compatibility if a model element is removed. Otherwise, if a new element is added or a attribute is adjusted, models are still compatible. 
I don't feel that it is the right choice to simply delete the loaded model. Especially not warning the user that their model will be lost is something to think about.

**Comment by Aran30** [comment]
@AlexanderNeumann  any thoughts?
