### ISSUE TITLE
Unable to edit "Content" field for Action Parameters

### ISSUE THREAD

**Issue by samuelvkwong** [rwth-acis/syncmeta#158]
<img width="1493" alt="image" src="https://github.com/rwth-acis/syncmeta/assets/130673431/24b56488-9d53-4283-adc9-20b4f0eb0e53">

When attempting to talk with OpenAPI service, the content field is needed to pass a parameter to an OpenAPI service call. The content field is missing.

**Comment by Aran30** [comment]
The current default metamodel is outdated and needs to be replaced.

**Comment by lakhoune** [comment]
Not an issue concerning syncmeta. This is defined in the metamodel
