### ISSUE TITLE
Resizing Elements is unpredictable

### ISSUE THREAD

**Issue by samuelvkwong** [rwth-acis/syncmeta#160]
<img width="1493" alt="image" src="https://github.com/rwth-acis/syncmeta/assets/130673431/683d3958-87d1-417a-8a68-871695d7f13d">

When attempting to resize elements, the element resize usually does not work as expected. Either the element enlarges much bigger than the intended element resize or it resizes in the opposite direction, e.g. enlarging results in shrinking.

**Comment by lakhoune** [comment]
I have never observed such a behaviour. Are you using a mouse or a trackpad? Which browser are you using?

**Comment by Aran30** [comment]
https://github.com/rwth-acis/syncmeta/assets/50965489/d82625d9-66de-46ff-9f70-1493280bf6f9

I also observed a similar bug. For me, I am using my mouse and am on firefox.
