### ISSUE TITLE
Text from fields sometimes duplicates itself

### ISSUE THREAD

**Issue by Aran30** [rwth-acis/syncmeta#161]
At times, in a model containing elements with attributes, the attributes themselves seem to duplicate. 

Here are some examples: 
![image](https://github.com/rwth-acis/syncmeta/assets/50965489/edf4657e-07ff-4b71-89b2-ee90f9ec31f3)

![image](https://github.com/rwth-acis/syncmeta/assets/50965489/9ee183a4-bc0e-4391-b878-ead71cf18bff)

Multiple users have joined this space. Maybe this has smth to do with it, as in other spaces in which i worked alone, this never occured.

**Comment by Aran30** [comment]
After trying it out on two different browsers, it seems to especially happen when reloading at the same time. 
So if there are two people in the space, but they joined at different times it's all good. If only one person refreshes at a time, it's all good. But if the two simultaneously refresh the page, the duplicating starts, and targets random fields. So loading up a space for multiple users at the same time seems to trigger the issue. Maybe something in how the yjs loading is handled is problematic?

**Comment by lakhoune** [comment]
It probably has something to do with how the text fields are initialized. I will look into it
