### ISSUE TITLE
[BUG] Unwanted casing in edges' field

### ISSUE THREAD

**Issue by Aran30** [rwth-acis/syncmeta#167]
When naming edges, the first letter will always automatically be upper case, even if not specified so. 

This is especially confusing, as in the canvas itself, the edge name is in lower case: 

![image](https://github.com/rwth-acis/syncmeta/assets/50965489/1973e05d-fecf-498e-9a7b-cf49ee4b79b0)

**Comment by lakhoune** [comment]
Affects Edge and Node labels only
