### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by phil-cd** [rwth-acis/syncmeta#47]
The following dependencies should be updated to the respectively specified version:
| Dependency | Update to this version or later | SyncMeta app or widgets? |
|---------------|-----------------------------------|------------------------------|
| jsrsasign       | 10.2.0 | app |
| ws | 1.1.5 | both |
| jquery-ui | 1.12.0 | widgets |
| ms | 0.7.1 | both |
| engine.io-client | 1.6.9 | both |
| debug | 2.6.9 | both |

Problems:
- engine.io-client v1.5.4 as currently used is a dependency of socket.io-client v1.3.7 which is required by y-websockets-client v8.0.16 that is currently used in SyncMeta. Updating y-websockets-client to the next version v9.0.0 would update the required version of socket.io-client to v^2.0.3 which would update engine.io-client to v~3.1.0. Problem with updating y-websockets-client is that **we would need to update Yjs to version 13** then (as it seems).
- ws v0.8.0 is also a dependency of engine.io-client v1.5.4.
- ms v0.6.2 is required by debug v1.0.4 which is again required by engine.io-client v1.5.4.
- debug v0.7.4 is required by socket.io-client which is required by y-websockets-client 
- jsrsasign v^8.0.12 is required by oidc-client v1.6.1 required by openidconnect-signin.

**Comment by phil-cd** [comment]
For Yjs 13 see the following issue: https://github.com/rwth-acis/syncmeta/issues/49

**Comment by lakhoune** [comment]
Out of this only jquery-ui still needs to be done
