### ISSUE TITLE
Upgrade to Yjs 13

### ISSUE THREAD

**Issue by phil-cd** [rwth-acis/syncmeta#49]
SyncMeta is still using Yjs 12 (from 2016). We should think about upgrading to Yjs 13.

Tasks:
- Import Yjs 13 into the SyncMeta widgets ✅
- Adapt to new syntax/API of Yjs for accessing shared content (via Y.Doc) ✅
- Text binding (Y.Text to input fields in SyncMeta, but also to Code Editor in CAE), not yet ported to Yjs 13 (related question on Gitter: https://gitter.im/Yjs/community?at=603404208031c8234bfa5273, related repository: https://github.com/yjs/y-textarea) ✅
- Update y-websocket ✅

Branch used for this: https://github.com/rwth-acis/syncmeta/tree/yjs13

**Comment by phil-cd** [comment]
Thanks to the help of @erdzan12 it is now at least already possible to import Yjs 13 into SyncMeta (https://github.com/rwth-acis/syncmeta/commit/78a80d65e813ff4b5ffb346e31b872cd1758e2e4).
In SyncMeta the templates for the widgets import the Yjs dependencies using script-tags.
As far as I understood, with Yjs 13 we are not able to do it in the same way, because we would need a bundler to transform the Yjs distributables so that they can be used in the browser (see https://gitter.im/Yjs/community?at=60ae925f688a2624b8b31c14).

The solution to import from "https://unpkg.com/yjs?module" is working, but maybe shouldn't be the final one.
Here is how it looks like right now:
```html
<script type="module">
    import * as Y from 'https://unpkg.com/yjs?module';
    import { WebsocketProvider } from 'https://unpkg.com/y-websocket?module';
    window.Y = Y;
    window.WebsocketProvider = WebsocketProvider;
</script>
```

**Comment by phil-cd** [comment]
We decided to wait before updating until the text binding is working.

**Comment by phil-cd** [comment]
Fork of y-websocket now exists in the rwth-acis organization: https://github.com/rwth-acis/y-websocket

**Comment by lakhoune** [comment]
Currently, most stuff was updated. There were some changes to be done to the y.share.* data since it is implemented in a different way in yjs13. I have drafted a PR that updates the code accordingly https://github.com/rwth-acis/syncmeta/pull/67

**Comment by lakhoune** [comment]
> We decided to wait before updating until the text binding is working.

Currently this is still an issue. The ytext.bind method is not provided by yjs13 and there seems to be no update regarding its addition

**Comment by lakhoune** [comment]
https://github.com/yjs/yjs/issues/160
Mentions moving to a new repo, but the new one is empty
