### ISSUE TITLE
Fix resizable

### ISSUE THREAD

**Issue by lakhoune** [rwth-acis/syncmeta#89]
The jquery-ui resizable library makes issues if we set the position of the element to absolute. 
However, due to jsPlumb requiring the position to be absolute, we removed the resizable code.

Need to find alternative libraries that do not rely on the relative position attribute

**Comment by AlexanderNeumann** [comment]
what about https://interactjs.io/ ?

**Comment by lakhoune** [comment]
Hi, yes it is actually implemented in #82
